//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientVentas.CotizacionesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CotizacionOutDTOOfCotizacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CotizacionOutDTOOfCotizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private int statusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVentas.CotizacionesService.Cotizacion dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientVentas.CotizacionesService.Cotizacion data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cotizacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cotizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaField;
        
        private float CotizacionActualField;
        
        private float CotizacionOficialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public float CotizacionActual {
            get {
                return this.CotizacionActualField;
            }
            set {
                if ((this.CotizacionActualField.Equals(value) != true)) {
                    this.CotizacionActualField = value;
                    this.RaisePropertyChanged("CotizacionActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float CotizacionOficial {
            get {
                return this.CotizacionOficialField;
            }
            set {
                if ((this.CotizacionOficialField.Equals(value) != true)) {
                    this.CotizacionOficialField = value;
                    this.RaisePropertyChanged("CotizacionOficial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CotizacionOutDTOOfListOfCotizacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CotizacionOutDTOOfListOfCotizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private int statusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVentas.CotizacionesService.Cotizacion[] dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientVentas.CotizacionesService.Cotizacion[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CotizacionOutDTOOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CotizacionOutDTOOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private int statusCodeField;
        
        private bool dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CotizacionesService.VentasSoap")]
    public interface VentasSoap {
        
        // CODEGEN: Generating message contract since element name fecha from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacionByFecha", ReplyAction="*")]
        ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse ObtenerCotizacionByFecha(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacionByFecha", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse> ObtenerCotizacionByFechaAsync(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizaciones", ReplyAction="*")]
        ClientVentas.CotizacionesService.ObtenerCotizacionesResponse ObtenerCotizaciones(ClientVentas.CotizacionesService.ObtenerCotizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionesResponse> ObtenerCotizacionesAsync(ClientVentas.CotizacionesService.ObtenerCotizacionesRequest request);
        
        // CODEGEN: Generating message contract since element name RegistrarCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizaciones", ReplyAction="*")]
        ClientVentas.CotizacionesService.RegistrarCotizacionesResponse RegistrarCotizaciones(ClientVentas.CotizacionesService.RegistrarCotizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.RegistrarCotizacionesResponse> RegistrarCotizacionesAsync(ClientVentas.CotizacionesService.RegistrarCotizacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionByFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionByFecha", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequestBody Body;
        
        public ObtenerCotizacionByFechaRequest() {
        }
        
        public ObtenerCotizacionByFechaRequest(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionByFechaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public ObtenerCotizacionByFechaRequestBody() {
        }
        
        public ObtenerCotizacionByFechaRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionByFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionByFechaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponseBody Body;
        
        public ObtenerCotizacionByFechaResponse() {
        }
        
        public ObtenerCotizacionByFechaResponse(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionByFechaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfCotizacion ObtenerCotizacionByFechaResult;
        
        public ObtenerCotizacionByFechaResponseBody() {
        }
        
        public ObtenerCotizacionByFechaResponseBody(ClientVentas.CotizacionesService.CotizacionOutDTOOfCotizacion ObtenerCotizacionByFechaResult) {
            this.ObtenerCotizacionByFechaResult = ObtenerCotizacionByFechaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.ObtenerCotizacionesRequestBody Body;
        
        public ObtenerCotizacionesRequest() {
        }
        
        public ObtenerCotizacionesRequest(ClientVentas.CotizacionesService.ObtenerCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerCotizacionesRequestBody {
        
        public ObtenerCotizacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.ObtenerCotizacionesResponseBody Body;
        
        public ObtenerCotizacionesResponse() {
        }
        
        public ObtenerCotizacionesResponse(ClientVentas.CotizacionesService.ObtenerCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfListOfCotizacion ObtenerCotizacionesResult;
        
        public ObtenerCotizacionesResponseBody() {
        }
        
        public ObtenerCotizacionesResponseBody(ClientVentas.CotizacionesService.CotizacionOutDTOOfListOfCotizacion ObtenerCotizacionesResult) {
            this.ObtenerCotizacionesResult = ObtenerCotizacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.RegistrarCotizacionesRequestBody Body;
        
        public RegistrarCotizacionesRequest() {
        }
        
        public RegistrarCotizacionesRequest(ClientVentas.CotizacionesService.RegistrarCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float cotizacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float cotizacionOficial;
        
        public RegistrarCotizacionesRequestBody() {
        }
        
        public RegistrarCotizacionesRequestBody(System.DateTime fecha, float cotizacion, float cotizacionOficial) {
            this.fecha = fecha;
            this.cotizacion = cotizacion;
            this.cotizacionOficial = cotizacionOficial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionesService.RegistrarCotizacionesResponseBody Body;
        
        public RegistrarCotizacionesResponse() {
        }
        
        public RegistrarCotizacionesResponse(ClientVentas.CotizacionesService.RegistrarCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfBoolean RegistrarCotizacionesResult;
        
        public RegistrarCotizacionesResponseBody() {
        }
        
        public RegistrarCotizacionesResponseBody(ClientVentas.CotizacionesService.CotizacionOutDTOOfBoolean RegistrarCotizacionesResult) {
            this.RegistrarCotizacionesResult = RegistrarCotizacionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentasSoapChannel : ClientVentas.CotizacionesService.VentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasSoapClient : System.ServiceModel.ClientBase<ClientVentas.CotizacionesService.VentasSoap>, ClientVentas.CotizacionesService.VentasSoap {
        
        public VentasSoapClient() {
        }
        
        public VentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse ClientVentas.CotizacionesService.VentasSoap.ObtenerCotizacionByFecha(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest request) {
            return base.Channel.ObtenerCotizacionByFecha(request);
        }
        
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfCotizacion ObtenerCotizacionByFecha(string fecha) {
            ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest inValue = new ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest();
            inValue.Body = new ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequestBody();
            inValue.Body.fecha = fecha;
            ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse retVal = ((ClientVentas.CotizacionesService.VentasSoap)(this)).ObtenerCotizacionByFecha(inValue);
            return retVal.Body.ObtenerCotizacionByFechaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse> ClientVentas.CotizacionesService.VentasSoap.ObtenerCotizacionByFechaAsync(ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest request) {
            return base.Channel.ObtenerCotizacionByFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionByFechaResponse> ObtenerCotizacionByFechaAsync(string fecha) {
            ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest inValue = new ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequest();
            inValue.Body = new ClientVentas.CotizacionesService.ObtenerCotizacionByFechaRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClientVentas.CotizacionesService.VentasSoap)(this)).ObtenerCotizacionByFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionesService.ObtenerCotizacionesResponse ClientVentas.CotizacionesService.VentasSoap.ObtenerCotizaciones(ClientVentas.CotizacionesService.ObtenerCotizacionesRequest request) {
            return base.Channel.ObtenerCotizaciones(request);
        }
        
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfListOfCotizacion ObtenerCotizaciones() {
            ClientVentas.CotizacionesService.ObtenerCotizacionesRequest inValue = new ClientVentas.CotizacionesService.ObtenerCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionesService.ObtenerCotizacionesRequestBody();
            ClientVentas.CotizacionesService.ObtenerCotizacionesResponse retVal = ((ClientVentas.CotizacionesService.VentasSoap)(this)).ObtenerCotizaciones(inValue);
            return retVal.Body.ObtenerCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionesResponse> ClientVentas.CotizacionesService.VentasSoap.ObtenerCotizacionesAsync(ClientVentas.CotizacionesService.ObtenerCotizacionesRequest request) {
            return base.Channel.ObtenerCotizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionesService.ObtenerCotizacionesResponse> ObtenerCotizacionesAsync() {
            ClientVentas.CotizacionesService.ObtenerCotizacionesRequest inValue = new ClientVentas.CotizacionesService.ObtenerCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionesService.ObtenerCotizacionesRequestBody();
            return ((ClientVentas.CotizacionesService.VentasSoap)(this)).ObtenerCotizacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionesService.RegistrarCotizacionesResponse ClientVentas.CotizacionesService.VentasSoap.RegistrarCotizaciones(ClientVentas.CotizacionesService.RegistrarCotizacionesRequest request) {
            return base.Channel.RegistrarCotizaciones(request);
        }
        
        public ClientVentas.CotizacionesService.CotizacionOutDTOOfBoolean RegistrarCotizaciones(System.DateTime fecha, float cotizacion, float cotizacionOficial) {
            ClientVentas.CotizacionesService.RegistrarCotizacionesRequest inValue = new ClientVentas.CotizacionesService.RegistrarCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionesService.RegistrarCotizacionesRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.cotizacion = cotizacion;
            inValue.Body.cotizacionOficial = cotizacionOficial;
            ClientVentas.CotizacionesService.RegistrarCotizacionesResponse retVal = ((ClientVentas.CotizacionesService.VentasSoap)(this)).RegistrarCotizaciones(inValue);
            return retVal.Body.RegistrarCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionesService.RegistrarCotizacionesResponse> ClientVentas.CotizacionesService.VentasSoap.RegistrarCotizacionesAsync(ClientVentas.CotizacionesService.RegistrarCotizacionesRequest request) {
            return base.Channel.RegistrarCotizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionesService.RegistrarCotizacionesResponse> RegistrarCotizacionesAsync(System.DateTime fecha, float cotizacion, float cotizacionOficial) {
            ClientVentas.CotizacionesService.RegistrarCotizacionesRequest inValue = new ClientVentas.CotizacionesService.RegistrarCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionesService.RegistrarCotizacionesRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.cotizacion = cotizacion;
            inValue.Body.cotizacionOficial = cotizacionOficial;
            return ((ClientVentas.CotizacionesService.VentasSoap)(this)).RegistrarCotizacionesAsync(inValue);
        }
    }
}
