//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePagos.ServicioPagos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfListOfDeuda", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfListOfDeuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientePagos.ServicioPagos.Deuda[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientePagos.ServicioPagos.Deuda[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Deuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        private float MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfListOfFactura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfListOfFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientePagos.ServicioPagos.Factura[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClientePagos.ServicioPagos.Factura[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        private float MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPagos.ServicioPagosSoap")]
    public interface ServicioPagosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        ClientePagos.ServicioPagos.VerDeudaResponse VerDeuda(ClientePagos.ServicioPagos.VerDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.ServicioPagos.VerDeudaResponse> VerDeudaAsync(ClientePagos.ServicioPagos.VerDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        ClientePagos.ServicioPagos.PagarDeudaResponse PagarDeuda(ClientePagos.ServicioPagos.PagarDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.ServicioPagos.PagarDeudaResponse> PagarDeudaAsync(ClientePagos.ServicioPagos.PagarDeudaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeuda", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServicioPagos.VerDeudaRequestBody Body;
        
        public VerDeudaRequest() {
        }
        
        public VerDeudaRequest(ClientePagos.ServicioPagos.VerDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido;
        
        public VerDeudaRequestBody() {
        }
        
        public VerDeudaRequestBody(string CI, string Nombres, string PrimerApellido, string SegundoApellido) {
            this.CI = CI;
            this.Nombres = Nombres;
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServicioPagos.VerDeudaResponseBody Body;
        
        public VerDeudaResponse() {
        }
        
        public VerDeudaResponse(ClientePagos.ServicioPagos.VerDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePagos.ServicioPagos.ResponseOfListOfDeuda VerDeudaResult;
        
        public VerDeudaResponseBody() {
        }
        
        public VerDeudaResponseBody(ClientePagos.ServicioPagos.ResponseOfListOfDeuda VerDeudaResult) {
            this.VerDeudaResult = VerDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeuda", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServicioPagos.PagarDeudaRequestBody Body;
        
        public PagarDeudaRequest() {
        }
        
        public PagarDeudaRequest(ClientePagos.ServicioPagos.PagarDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float Monto;
        
        public PagarDeudaRequestBody() {
        }
        
        public PagarDeudaRequestBody(string CI, string Nombres, string PrimerApellido, string SegundoApellido, float Monto) {
            this.CI = CI;
            this.Nombres = Nombres;
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.Monto = Monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServicioPagos.PagarDeudaResponseBody Body;
        
        public PagarDeudaResponse() {
        }
        
        public PagarDeudaResponse(ClientePagos.ServicioPagos.PagarDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePagos.ServicioPagos.ResponseOfListOfFactura PagarDeudaResult;
        
        public PagarDeudaResponseBody() {
        }
        
        public PagarDeudaResponseBody(ClientePagos.ServicioPagos.ResponseOfListOfFactura PagarDeudaResult) {
            this.PagarDeudaResult = PagarDeudaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioPagosSoapChannel : ClientePagos.ServicioPagos.ServicioPagosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPagosSoapClient : System.ServiceModel.ClientBase<ClientePagos.ServicioPagos.ServicioPagosSoap>, ClientePagos.ServicioPagos.ServicioPagosSoap {
        
        public ServicioPagosSoapClient() {
        }
        
        public ServicioPagosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPagosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.ServicioPagos.VerDeudaResponse ClientePagos.ServicioPagos.ServicioPagosSoap.VerDeuda(ClientePagos.ServicioPagos.VerDeudaRequest request) {
            return base.Channel.VerDeuda(request);
        }
        
        public ClientePagos.ServicioPagos.ResponseOfListOfDeuda VerDeuda(string CI, string Nombres, string PrimerApellido, string SegundoApellido) {
            ClientePagos.ServicioPagos.VerDeudaRequest inValue = new ClientePagos.ServicioPagos.VerDeudaRequest();
            inValue.Body = new ClientePagos.ServicioPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            ClientePagos.ServicioPagos.VerDeudaResponse retVal = ((ClientePagos.ServicioPagos.ServicioPagosSoap)(this)).VerDeuda(inValue);
            return retVal.Body.VerDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.ServicioPagos.VerDeudaResponse> ClientePagos.ServicioPagos.ServicioPagosSoap.VerDeudaAsync(ClientePagos.ServicioPagos.VerDeudaRequest request) {
            return base.Channel.VerDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.ServicioPagos.VerDeudaResponse> VerDeudaAsync(string CI, string Nombres, string PrimerApellido, string SegundoApellido) {
            ClientePagos.ServicioPagos.VerDeudaRequest inValue = new ClientePagos.ServicioPagos.VerDeudaRequest();
            inValue.Body = new ClientePagos.ServicioPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            return ((ClientePagos.ServicioPagos.ServicioPagosSoap)(this)).VerDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.ServicioPagos.PagarDeudaResponse ClientePagos.ServicioPagos.ServicioPagosSoap.PagarDeuda(ClientePagos.ServicioPagos.PagarDeudaRequest request) {
            return base.Channel.PagarDeuda(request);
        }
        
        public ClientePagos.ServicioPagos.ResponseOfListOfFactura PagarDeuda(string CI, string Nombres, string PrimerApellido, string SegundoApellido, float Monto) {
            ClientePagos.ServicioPagos.PagarDeudaRequest inValue = new ClientePagos.ServicioPagos.PagarDeudaRequest();
            inValue.Body = new ClientePagos.ServicioPagos.PagarDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Monto = Monto;
            ClientePagos.ServicioPagos.PagarDeudaResponse retVal = ((ClientePagos.ServicioPagos.ServicioPagosSoap)(this)).PagarDeuda(inValue);
            return retVal.Body.PagarDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.ServicioPagos.PagarDeudaResponse> ClientePagos.ServicioPagos.ServicioPagosSoap.PagarDeudaAsync(ClientePagos.ServicioPagos.PagarDeudaRequest request) {
            return base.Channel.PagarDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.ServicioPagos.PagarDeudaResponse> PagarDeudaAsync(string CI, string Nombres, string PrimerApellido, string SegundoApellido, float Monto) {
            ClientePagos.ServicioPagos.PagarDeudaRequest inValue = new ClientePagos.ServicioPagos.PagarDeudaRequest();
            inValue.Body = new ClientePagos.ServicioPagos.PagarDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Monto = Monto;
            return ((ClientePagos.ServicioPagos.ServicioPagosSoap)(this)).PagarDeudaAsync(inValue);
        }
    }
}
