//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSEGIP.PersonasService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDTOOfPersona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseDTOOfPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private int statusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteSEGIP.PersonasService.Persona dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteSEGIP.PersonasService.Persona data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ci {
            get {
                return this.ciField;
            }
            set {
                if ((object.ReferenceEquals(this.ciField, value) != true)) {
                    this.ciField = value;
                    this.RaisePropertyChanged("ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDTOOfListOfPersona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseDTOOfListOfPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private int statusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteSEGIP.PersonasService.Persona[] dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                if ((this.statusCodeField.Equals(value) != true)) {
                    this.statusCodeField = value;
                    this.RaisePropertyChanged("statusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteSEGIP.PersonasService.Persona[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonasService.PersonasServiceSoap")]
    public interface PersonasServiceSoap {
        
        // CODEGEN: Generating message contract since element name numeroDocumento from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        ClienteSEGIP.PersonasService.BuscarPersonaCIResponse BuscarPersonaCI(ClienteSEGIP.PersonasService.BuscarPersonaCIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonaCIResponse> BuscarPersonaCIAsync(ClienteSEGIP.PersonasService.BuscarPersonaCIRequest request);
        
        // CODEGEN: Generating message contract since element name PrimerApellido from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        ClienteSEGIP.PersonasService.BuscarPersonasResponse BuscarPersonas(ClienteSEGIP.PersonasService.BuscarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonasResponse> BuscarPersonasAsync(ClienteSEGIP.PersonasService.BuscarPersonasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCI", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSEGIP.PersonasService.BuscarPersonaCIRequestBody Body;
        
        public BuscarPersonaCIRequest() {
        }
        
        public BuscarPersonaCIRequest(ClienteSEGIP.PersonasService.BuscarPersonaCIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroDocumento;
        
        public BuscarPersonaCIRequestBody() {
        }
        
        public BuscarPersonaCIRequestBody(string numeroDocumento) {
            this.numeroDocumento = numeroDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCIResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSEGIP.PersonasService.BuscarPersonaCIResponseBody Body;
        
        public BuscarPersonaCIResponse() {
        }
        
        public BuscarPersonaCIResponse(ClienteSEGIP.PersonasService.BuscarPersonaCIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteSEGIP.PersonasService.ResponseDTOOfPersona BuscarPersonaCIResult;
        
        public BuscarPersonaCIResponseBody() {
        }
        
        public BuscarPersonaCIResponseBody(ClienteSEGIP.PersonasService.ResponseDTOOfPersona BuscarPersonaCIResult) {
            this.BuscarPersonaCIResult = BuscarPersonaCIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSEGIP.PersonasService.BuscarPersonasRequestBody Body;
        
        public BuscarPersonasRequest() {
        }
        
        public BuscarPersonasRequest(ClienteSEGIP.PersonasService.BuscarPersonasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres;
        
        public BuscarPersonasRequestBody() {
        }
        
        public BuscarPersonasRequestBody(string PrimerApellido, string SegundoApellido, string Nombres) {
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.Nombres = Nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSEGIP.PersonasService.BuscarPersonasResponseBody Body;
        
        public BuscarPersonasResponse() {
        }
        
        public BuscarPersonasResponse(ClienteSEGIP.PersonasService.BuscarPersonasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteSEGIP.PersonasService.ResponseDTOOfListOfPersona BuscarPersonasResult;
        
        public BuscarPersonasResponseBody() {
        }
        
        public BuscarPersonasResponseBody(ClienteSEGIP.PersonasService.ResponseDTOOfListOfPersona BuscarPersonasResult) {
            this.BuscarPersonasResult = BuscarPersonasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonasServiceSoapChannel : ClienteSEGIP.PersonasService.PersonasServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonasServiceSoapClient : System.ServiceModel.ClientBase<ClienteSEGIP.PersonasService.PersonasServiceSoap>, ClienteSEGIP.PersonasService.PersonasServiceSoap {
        
        public PersonasServiceSoapClient() {
        }
        
        public PersonasServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonasServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonasServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonasServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSEGIP.PersonasService.BuscarPersonaCIResponse ClienteSEGIP.PersonasService.PersonasServiceSoap.BuscarPersonaCI(ClienteSEGIP.PersonasService.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCI(request);
        }
        
        public ClienteSEGIP.PersonasService.ResponseDTOOfPersona BuscarPersonaCI(string numeroDocumento) {
            ClienteSEGIP.PersonasService.BuscarPersonaCIRequest inValue = new ClienteSEGIP.PersonasService.BuscarPersonaCIRequest();
            inValue.Body = new ClienteSEGIP.PersonasService.BuscarPersonaCIRequestBody();
            inValue.Body.numeroDocumento = numeroDocumento;
            ClienteSEGIP.PersonasService.BuscarPersonaCIResponse retVal = ((ClienteSEGIP.PersonasService.PersonasServiceSoap)(this)).BuscarPersonaCI(inValue);
            return retVal.Body.BuscarPersonaCIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonaCIResponse> ClienteSEGIP.PersonasService.PersonasServiceSoap.BuscarPersonaCIAsync(ClienteSEGIP.PersonasService.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCIAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonaCIResponse> BuscarPersonaCIAsync(string numeroDocumento) {
            ClienteSEGIP.PersonasService.BuscarPersonaCIRequest inValue = new ClienteSEGIP.PersonasService.BuscarPersonaCIRequest();
            inValue.Body = new ClienteSEGIP.PersonasService.BuscarPersonaCIRequestBody();
            inValue.Body.numeroDocumento = numeroDocumento;
            return ((ClienteSEGIP.PersonasService.PersonasServiceSoap)(this)).BuscarPersonaCIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSEGIP.PersonasService.BuscarPersonasResponse ClienteSEGIP.PersonasService.PersonasServiceSoap.BuscarPersonas(ClienteSEGIP.PersonasService.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonas(request);
        }
        
        public ClienteSEGIP.PersonasService.ResponseDTOOfListOfPersona BuscarPersonas(string PrimerApellido, string SegundoApellido, string Nombres) {
            ClienteSEGIP.PersonasService.BuscarPersonasRequest inValue = new ClienteSEGIP.PersonasService.BuscarPersonasRequest();
            inValue.Body = new ClienteSEGIP.PersonasService.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            ClienteSEGIP.PersonasService.BuscarPersonasResponse retVal = ((ClienteSEGIP.PersonasService.PersonasServiceSoap)(this)).BuscarPersonas(inValue);
            return retVal.Body.BuscarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonasResponse> ClienteSEGIP.PersonasService.PersonasServiceSoap.BuscarPersonasAsync(ClienteSEGIP.PersonasService.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSEGIP.PersonasService.BuscarPersonasResponse> BuscarPersonasAsync(string PrimerApellido, string SegundoApellido, string Nombres) {
            ClienteSEGIP.PersonasService.BuscarPersonasRequest inValue = new ClienteSEGIP.PersonasService.BuscarPersonasRequest();
            inValue.Body = new ClienteSEGIP.PersonasService.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            return ((ClienteSEGIP.PersonasService.PersonasServiceSoap)(this)).BuscarPersonasAsync(inValue);
        }
    }
}
