//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSeduinfo.SeduinfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfEstudiante", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfEstudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteSeduinfo.SeduinfoService.Estudiante DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteSeduinfo.SeduinfoService.Estudiante Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        private double PromedioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Promedio {
            get {
                return this.PromedioField;
            }
            set {
                if ((this.PromedioField.Equals(value) != true)) {
                    this.PromedioField = value;
                    this.RaisePropertyChanged("Promedio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfTutor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfTutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteSeduinfo.SeduinfoService.Tutor DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ClienteSeduinfo.SeduinfoService.Tutor Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoTutorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreEstudiante {
            get {
                return this.NombreEstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstudianteField, value) != true)) {
                    this.NombreEstudianteField = value;
                    this.RaisePropertyChanged("NombreEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TutorAsignado {
            get {
                return this.TutorAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorAsignadoField, value) != true)) {
                    this.TutorAsignadoField = value;
                    this.RaisePropertyChanged("TutorAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CorreoTutor {
            get {
                return this.CorreoTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoTutorField, value) != true)) {
                    this.CorreoTutorField = value;
                    this.RaisePropertyChanged("CorreoTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TelefonoTutor {
            get {
                return this.TelefonoTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoTutorField, value) != true)) {
                    this.TelefonoTutorField = value;
                    this.RaisePropertyChanged("TelefonoTutor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeduinfoService.SeduInfoServiceSoap")]
    public interface SeduInfoServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosAcademicos", ReplyAction="*")]
        ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse ObtenerDatosAcademicos(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosAcademicos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse> ObtenerDatosAcademicosAsync(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosTutor", ReplyAction="*")]
        ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse ObtenerDatosTutor(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosTutor", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse> ObtenerDatosTutorAsync(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosAcademicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosAcademicos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequestBody Body;
        
        public ObtenerDatosAcademicosRequest() {
        }
        
        public ObtenerDatosAcademicosRequest(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosAcademicosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosAcademicosRequestBody() {
        }
        
        public ObtenerDatosAcademicosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosAcademicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosAcademicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponseBody Body;
        
        public ObtenerDatosAcademicosResponse() {
        }
        
        public ObtenerDatosAcademicosResponse(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosAcademicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteSeduinfo.SeduinfoService.ResponseOfEstudiante ObtenerDatosAcademicosResult;
        
        public ObtenerDatosAcademicosResponseBody() {
        }
        
        public ObtenerDatosAcademicosResponseBody(ClienteSeduinfo.SeduinfoService.ResponseOfEstudiante ObtenerDatosAcademicosResult) {
            this.ObtenerDatosAcademicosResult = ObtenerDatosAcademicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosTutor", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequestBody Body;
        
        public ObtenerDatosTutorRequest() {
        }
        
        public ObtenerDatosTutorRequest(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosTutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosTutorRequestBody() {
        }
        
        public ObtenerDatosTutorRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosTutorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponseBody Body;
        
        public ObtenerDatosTutorResponse() {
        }
        
        public ObtenerDatosTutorResponse(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosTutorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteSeduinfo.SeduinfoService.ResponseOfTutor ObtenerDatosTutorResult;
        
        public ObtenerDatosTutorResponseBody() {
        }
        
        public ObtenerDatosTutorResponseBody(ClienteSeduinfo.SeduinfoService.ResponseOfTutor ObtenerDatosTutorResult) {
            this.ObtenerDatosTutorResult = ObtenerDatosTutorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeduInfoServiceSoapChannel : ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeduInfoServiceSoapClient : System.ServiceModel.ClientBase<ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap>, ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap {
        
        public SeduInfoServiceSoapClient() {
        }
        
        public SeduInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeduInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeduInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeduInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap.ObtenerDatosAcademicos(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest request) {
            return base.Channel.ObtenerDatosAcademicos(request);
        }
        
        public ClienteSeduinfo.SeduinfoService.ResponseOfEstudiante ObtenerDatosAcademicos(string CI) {
            ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest inValue = new ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest();
            inValue.Body = new ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequestBody();
            inValue.Body.CI = CI;
            ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse retVal = ((ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap)(this)).ObtenerDatosAcademicos(inValue);
            return retVal.Body.ObtenerDatosAcademicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse> ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap.ObtenerDatosAcademicosAsync(ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest request) {
            return base.Channel.ObtenerDatosAcademicosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosResponse> ObtenerDatosAcademicosAsync(string CI) {
            ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest inValue = new ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequest();
            inValue.Body = new ClienteSeduinfo.SeduinfoService.ObtenerDatosAcademicosRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap)(this)).ObtenerDatosAcademicosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap.ObtenerDatosTutor(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest request) {
            return base.Channel.ObtenerDatosTutor(request);
        }
        
        public ClienteSeduinfo.SeduinfoService.ResponseOfTutor ObtenerDatosTutor(string CI) {
            ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest inValue = new ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest();
            inValue.Body = new ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequestBody();
            inValue.Body.CI = CI;
            ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse retVal = ((ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap)(this)).ObtenerDatosTutor(inValue);
            return retVal.Body.ObtenerDatosTutorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse> ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap.ObtenerDatosTutorAsync(ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest request) {
            return base.Channel.ObtenerDatosTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorResponse> ObtenerDatosTutorAsync(string CI) {
            ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest inValue = new ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequest();
            inValue.Body = new ClienteSeduinfo.SeduinfoService.ObtenerDatosTutorRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteSeduinfo.SeduinfoService.SeduInfoServiceSoap)(this)).ObtenerDatosTutorAsync(inValue);
        }
    }
}
