//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientVentas.CotizacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cotizacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cotizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaField;
        
        private float CotizacionActualField;
        
        private float CotizacionOficialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public float CotizacionActual {
            get {
                return this.CotizacionActualField;
            }
            set {
                if ((this.CotizacionActualField.Equals(value) != true)) {
                    this.CotizacionActualField = value;
                    this.RaisePropertyChanged("CotizacionActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float CotizacionOficial {
            get {
                return this.CotizacionOficialField;
            }
            set {
                if ((this.CotizacionOficialField.Equals(value) != true)) {
                    this.CotizacionOficialField = value;
                    this.RaisePropertyChanged("CotizacionOficial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CotizacionService.VentasSoap")]
    public interface VentasSoap {
        
        // CODEGEN: Generating message contract since element name fecha from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        ClientVentas.CotizacionService.ObtenerCotizacionResponse ObtenerCotizacion(ClientVentas.CotizacionService.ObtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionResponse> ObtenerCotizacionAsync(ClientVentas.CotizacionService.ObtenerCotizacionRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizaciones", ReplyAction="*")]
        ClientVentas.CotizacionService.ObtenerCotizacionesResponse ObtenerCotizaciones(ClientVentas.CotizacionService.ObtenerCotizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionesResponse> ObtenerCotizacionesAsync(ClientVentas.CotizacionService.ObtenerCotizacionesRequest request);
        
        // CODEGEN: Generating message contract since element name RegistrarCotizacionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizaciones", ReplyAction="*")]
        ClientVentas.CotizacionService.RegistrarCotizacionesResponse RegistrarCotizaciones(ClientVentas.CotizacionService.RegistrarCotizacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.RegistrarCotizacionesResponse> RegistrarCotizacionesAsync(ClientVentas.CotizacionService.RegistrarCotizacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.ObtenerCotizacionRequestBody Body;
        
        public ObtenerCotizacionRequest() {
        }
        
        public ObtenerCotizacionRequest(ClientVentas.CotizacionService.ObtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public ObtenerCotizacionRequestBody() {
        }
        
        public ObtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.ObtenerCotizacionResponseBody Body;
        
        public ObtenerCotizacionResponse() {
        }
        
        public ObtenerCotizacionResponse(ClientVentas.CotizacionService.ObtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionService.Cotizacion ObtenerCotizacionResult;
        
        public ObtenerCotizacionResponseBody() {
        }
        
        public ObtenerCotizacionResponseBody(ClientVentas.CotizacionService.Cotizacion ObtenerCotizacionResult) {
            this.ObtenerCotizacionResult = ObtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.ObtenerCotizacionesRequestBody Body;
        
        public ObtenerCotizacionesRequest() {
        }
        
        public ObtenerCotizacionesRequest(ClientVentas.CotizacionService.ObtenerCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerCotizacionesRequestBody {
        
        public ObtenerCotizacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.ObtenerCotizacionesResponseBody Body;
        
        public ObtenerCotizacionesResponse() {
        }
        
        public ObtenerCotizacionesResponse(ClientVentas.CotizacionService.ObtenerCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionService.Cotizacion[] ObtenerCotizacionesResult;
        
        public ObtenerCotizacionesResponseBody() {
        }
        
        public ObtenerCotizacionesResponseBody(ClientVentas.CotizacionService.Cotizacion[] ObtenerCotizacionesResult) {
            this.ObtenerCotizacionesResult = ObtenerCotizacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizaciones", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.RegistrarCotizacionesRequestBody Body;
        
        public RegistrarCotizacionesRequest() {
        }
        
        public RegistrarCotizacionesRequest(ClientVentas.CotizacionService.RegistrarCotizacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float Cotizacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float CotizacionOficial;
        
        public RegistrarCotizacionesRequestBody() {
        }
        
        public RegistrarCotizacionesRequestBody(System.DateTime Fecha, float Cotizacion, float CotizacionOficial) {
            this.Fecha = Fecha;
            this.Cotizacion = Cotizacion;
            this.CotizacionOficial = CotizacionOficial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientVentas.CotizacionService.RegistrarCotizacionesResponseBody Body;
        
        public RegistrarCotizacionesResponse() {
        }
        
        public RegistrarCotizacionesResponse(ClientVentas.CotizacionService.RegistrarCotizacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientVentas.CotizacionService.Cotizacion[] RegistrarCotizacionesResult;
        
        public RegistrarCotizacionesResponseBody() {
        }
        
        public RegistrarCotizacionesResponseBody(ClientVentas.CotizacionService.Cotizacion[] RegistrarCotizacionesResult) {
            this.RegistrarCotizacionesResult = RegistrarCotizacionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentasSoapChannel : ClientVentas.CotizacionService.VentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasSoapClient : System.ServiceModel.ClientBase<ClientVentas.CotizacionService.VentasSoap>, ClientVentas.CotizacionService.VentasSoap {
        
        public VentasSoapClient() {
        }
        
        public VentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionService.ObtenerCotizacionResponse ClientVentas.CotizacionService.VentasSoap.ObtenerCotizacion(ClientVentas.CotizacionService.ObtenerCotizacionRequest request) {
            return base.Channel.ObtenerCotizacion(request);
        }
        
        public ClientVentas.CotizacionService.Cotizacion ObtenerCotizacion(string fecha) {
            ClientVentas.CotizacionService.ObtenerCotizacionRequest inValue = new ClientVentas.CotizacionService.ObtenerCotizacionRequest();
            inValue.Body = new ClientVentas.CotizacionService.ObtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            ClientVentas.CotizacionService.ObtenerCotizacionResponse retVal = ((ClientVentas.CotizacionService.VentasSoap)(this)).ObtenerCotizacion(inValue);
            return retVal.Body.ObtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionResponse> ClientVentas.CotizacionService.VentasSoap.ObtenerCotizacionAsync(ClientVentas.CotizacionService.ObtenerCotizacionRequest request) {
            return base.Channel.ObtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionResponse> ObtenerCotizacionAsync(string fecha) {
            ClientVentas.CotizacionService.ObtenerCotizacionRequest inValue = new ClientVentas.CotizacionService.ObtenerCotizacionRequest();
            inValue.Body = new ClientVentas.CotizacionService.ObtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClientVentas.CotizacionService.VentasSoap)(this)).ObtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionService.ObtenerCotizacionesResponse ClientVentas.CotizacionService.VentasSoap.ObtenerCotizaciones(ClientVentas.CotizacionService.ObtenerCotizacionesRequest request) {
            return base.Channel.ObtenerCotizaciones(request);
        }
        
        public ClientVentas.CotizacionService.Cotizacion[] ObtenerCotizaciones() {
            ClientVentas.CotizacionService.ObtenerCotizacionesRequest inValue = new ClientVentas.CotizacionService.ObtenerCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionService.ObtenerCotizacionesRequestBody();
            ClientVentas.CotizacionService.ObtenerCotizacionesResponse retVal = ((ClientVentas.CotizacionService.VentasSoap)(this)).ObtenerCotizaciones(inValue);
            return retVal.Body.ObtenerCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionesResponse> ClientVentas.CotizacionService.VentasSoap.ObtenerCotizacionesAsync(ClientVentas.CotizacionService.ObtenerCotizacionesRequest request) {
            return base.Channel.ObtenerCotizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionService.ObtenerCotizacionesResponse> ObtenerCotizacionesAsync() {
            ClientVentas.CotizacionService.ObtenerCotizacionesRequest inValue = new ClientVentas.CotizacionService.ObtenerCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionService.ObtenerCotizacionesRequestBody();
            return ((ClientVentas.CotizacionService.VentasSoap)(this)).ObtenerCotizacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientVentas.CotizacionService.RegistrarCotizacionesResponse ClientVentas.CotizacionService.VentasSoap.RegistrarCotizaciones(ClientVentas.CotizacionService.RegistrarCotizacionesRequest request) {
            return base.Channel.RegistrarCotizaciones(request);
        }
        
        public ClientVentas.CotizacionService.Cotizacion[] RegistrarCotizaciones(System.DateTime Fecha, float Cotizacion, float CotizacionOficial) {
            ClientVentas.CotizacionService.RegistrarCotizacionesRequest inValue = new ClientVentas.CotizacionService.RegistrarCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionService.RegistrarCotizacionesRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.Cotizacion = Cotizacion;
            inValue.Body.CotizacionOficial = CotizacionOficial;
            ClientVentas.CotizacionService.RegistrarCotizacionesResponse retVal = ((ClientVentas.CotizacionService.VentasSoap)(this)).RegistrarCotizaciones(inValue);
            return retVal.Body.RegistrarCotizacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientVentas.CotizacionService.RegistrarCotizacionesResponse> ClientVentas.CotizacionService.VentasSoap.RegistrarCotizacionesAsync(ClientVentas.CotizacionService.RegistrarCotizacionesRequest request) {
            return base.Channel.RegistrarCotizacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientVentas.CotizacionService.RegistrarCotizacionesResponse> RegistrarCotizacionesAsync(System.DateTime Fecha, float Cotizacion, float CotizacionOficial) {
            ClientVentas.CotizacionService.RegistrarCotizacionesRequest inValue = new ClientVentas.CotizacionService.RegistrarCotizacionesRequest();
            inValue.Body = new ClientVentas.CotizacionService.RegistrarCotizacionesRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.Cotizacion = Cotizacion;
            inValue.Body.CotizacionOficial = CotizacionOficial;
            return ((ClientVentas.CotizacionService.VentasSoap)(this)).RegistrarCotizacionesAsync(inValue);
        }
    }
}
